[package]
name = "brewdesk"
version = "0.1.0"
description = "A lightweight Homebrew desktop manager"
edition = "2021"
license = "MIT"
repository = "https://github.com/Tsing-duan/brewdesk-homebrew"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
uuid = { version = "1", features = ["v4"] }
libc = "0.2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
debug = false
strip = "symbols"
lto = "thin"
codegen-units = 1
